apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  QUESTION_PORT: "3001"
  USER_PORT: "3002"
  MATCHING_PORT: "8080"
  COLLAB_PORT: "8081"
  GATEWAY_PORT: "4000"
  ENV: "PROD"
  REACT_APP_QUESTION_API_URL: "http://question-service:3001"
  REACT_APP_USER_API_URL: "http://user-service:3002"
  REACT_APP_MATCHING_API_URL: "http://matching-service:8080"
  REACT_APP_COLLAB_WS_URL: "ws://collaboration-service:8081"
  REACT_APP_COLLAB_API_URL: "http://collaboration-service:8081"
  REACT_APP_GATEWAY_URL: "http://api-gateway:4000/api"