apiVersion: apps/v1
kind: Deployment
metadata:
  name: collaboration-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collaboration-service
  template:
    metadata:
      labels:
        app: collaboration-service
    spec:
      containers:
      - name: collaboration-service
        image: wuemily/collaboration-service:latest
        ports:
        - containerPort: 8083
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        env:
        - name: PORT
          value: "8083"
        envFrom:
            - configMapRef:
                name: app-config
